### ISSUE TITLE
Is there any limitation on the length of sentence? I tried to evaluate this on a paragraph of 719 words but the model only performed NER on the first 100 words! 

### ISSUE THREAD

**Issue by workPA** [asahi417/tner#16]

**Comment by asahi417** [comment]
Hi, each NER model we released in the library has a maximum number of token they can handle and exceeded tokens will be disregarded. This limitation comes from the underlying language models. For example BERT's maximum length is 128 and RoBERTa's maximum length is 512. If you need NER model that can handle long sentence, you might want to try finetuning language model with longer token length (Longformer. etc), or split your input into chunks beforehand.

**Comment by asahi417** [comment]
In practice, we split a long document into sentences and feed them separately to NER model as NER model usually don't need wider context (whole document).
