### ISSUE TITLE
Why are some packages pinned to rather old versions?

### ISSUE THREAD

**Issue by johann-petrak** [asahi417/tner#18]
The requirements file states that some packages need to get installed with very old versions, e.g. jinja2==2.11.3  This is a problem in situations where one would like to use the tner library together with other code which uses or needs much more recent versions. 
Are the specific versions in the requirements file actually essential or could the be turned into minimal versions or a combination of more recent versions that also works be found? 

Installing tner uninstalled two packages from my environment and replaced them with older versions:
* Jinja2 3.0.3 was replaced with 2.11.3
* click 8.0.3 was replaced with 7.1.2

**Comment by asahi417** [comment]
For those two libraries (jinjia2 and click), we need them for the tner's local demo only, so if you use it for model training or inference only, you might even ignore them.

**Comment by johann-petrak** [comment]
I think the ideal solution for this would be to define an extra, e.g. "demo" so that by default these dependencies do not get installed, but `pip install tner[demo]` would install everything? 

As I said the problem is that if a user makes tner part of their environment and does `pip install tner` as part of a lot of other pip installs, then if tner gets installed after others, it may change the versions of jinja2 or click which were previously installed by the other install commands. The user may not even realize this is happening! 

The only way to make it possible to tell pip not to install those dependencies is by not including them (and letting the user install manually if needed) or by making them an extra.

**Comment by asahi417** [comment]
Extra libraries are now put as optional. You need `pip install tner[demo]` to install all the requirement, and otherwise they will be skipped.
