### ISSUE TITLE
Running tner-train does not work

### ISSUE THREAD

**Issue by johann-petrak** [asahi417/tner#19]
After `pip install tner`: Running `tner-train -h` shows 

```
Traceback (most recent call last):
  File "/home/johann/software/anaconda/envs/gatenlp-37/bin/tner-train", line 5, in <module>
    from tner_cl.train import main
ModuleNotFoundError: No module named 'tner_cl'
```

**Comment by asahi417** [comment]
I have checked and if you installed it via source (git clone https://github.com/asahi417/tner && cd tner && pip install .), it worked but it seems that pip install do not include the console_scripts.
https://github.com/pypa/pip/issues/9110

**Comment by johann-petrak** [comment]
I think this happens because setup will only install the content of the tner subdirectory on the target system. If you look at what `python setup.py sdist bdist_wheel` creates you will see that tner_cl is not included in the distribution. 

This is by design as setup uses the find_packages method to find all packages in the directory. Since tner_cl does not have an `__init__.py` file, it is not recognized as package. 

Personally I think it would not be worth to create another package just for the commands, the modules could get moved to the tner package and setup changed to run them from there.

**Comment by asahi417** [comment]
Command line tools are now inside of the library.
