### ISSUE TITLE
Checkpoint directory cleanup: all directories starting with the same prefix are removed

### ISSUE THREAD

**Issue by johann-petrak** [asahi417/tner#21]
When specifying a directory name "abc", then https://github.com/asahi417/tner/blob/869fca445e6067b3e770d42214e73ead40fef6d5/tner/checkpoint_versioning.py#L88 also causes all directories that start with "abc" to get removed. I guess that is not intended.

A solution could be to append the platform-specific path separator if it is not already there.

BTW: the code in checkpoint_versioning.py is not portable as it assumes that the slash is the path separator.

**Comment by asahi417** [comment]
Indeed, this is not an ideal behavior... I would employ what's you suggested to make sure that we don't remove checkpoint directories that share same prefix.
