### ISSUE TITLE
Strange prediction bahavior

### ISSUE THREAD

**Issue by JaouadMousser** [asahi417/tner#22]
Hi Asahi,

I am having an issue related to a model I trained using tner. I used a custom dataset with labels like "INCEPTION_DATE", "PARNTER_COUNTRY" etc. The training itself seems to go well, but when I tried to call the predict function, I start getting some different labels like "Date", "City" and other entities which were not in my data.

Is there anything I am missing here?

I would appreciate any advise.

**Comment by johann-petrak** [comment]
I think this may happen when a model that has been finetuned for token classification gets used. I am not sure what exactly is going on here: if the model includes a classification head, will tner use that head or will it use the base transformer with its own head for the given data? (the latter would make much more sense to me)

**Comment by johann-petrak** [comment]
Oh, sorry, I think my issue is actually different, what I see seems to happen in https://github.com/asahi417/tner/blob/83eb39f4afb8ef0d229f10e7546c63760d8d872d/tner/get_dataset.py#L429 where certain known types are mapped to some pre-defined type. 

This is not a useful behavior in situations where we really need exactly the types in the dataset, could we please make this mapping optional?

**Comment by JaouadMousser** [comment]
Thanks Johan. I will try to deactivate the mapping part. But I am not sure it is going to solve the problem given that my labels are not part of the map provided in the code.

**Comment by johann-petrak** [comment]
@JaouadMousser which model do you start with? is it one from huggingface hub?

**Comment by johann-petrak** [comment]
OK, to me this looks very weird, there should be now way how other chunk labels should get used with that base model. Is this reproducable?

**Comment by JaouadMousser** [comment]
Hi, 

I could find where the problem is coming from. The code is expecting two-parts  labels like B-ORG. In my case I have three-parts labels like "B-INCEPTION-DATE", "B-PERIOD-DATE", etc.. The decode_ner_tags functions splits this labels and take the last part of it. In my case, since I have many labels ending by "-DATE" or "-CITY", etc, the predict function returns "DATE" for all label ending by DATE, etc,
@johann-petrak, @asahi417  thank you for your support.

**Comment by asahi417** [comment]
Hi @JaouadMousser 
Thank you for figuring out the issue. This should be handled in more wise way indeed (eg. take the first part of "{B,I}-" and keep the rest). I'll add this to my todo list for next version. Really appreciate it!
