### ISSUE TITLE
Could you please add a comment to the title of the model under this website?

### ISSUE THREAD

**Issue by 645187919** [asahi417/tner#24]
https://huggingface.co/tner

**Comment by asahi417** [comment]
Thank you for mentioning it! As the number of models increased a lot recently, we moved most of the models from my personal account to a group named tner. According to huggingface, the old model path should be redirected to the new link, but this is apparently not working unfortunately... 
We will soon announce the model migration and will enrich description on the organization.

**Comment by asahi417** [comment]
The huggingface organization is now up-to-date! We will release more models and datasets there soon.
https://huggingface.co/tner
