### ISSUE TITLE
Using a Spacy Tokenizer and calling TNER's prediction on it

### ISSUE THREAD

**Issue by Akshay0799** [asahi417/tner#25]
I'm trying to integrate TNER with Spacy. Would it be possible for me to use spacy's tokenization and then use TNER to only call the predictions on the spacy tokens ?

**Comment by asahi417** [comment]
Yes and that's actually recommend. If you pass a string, that will be tokenized by half-space, and if you provide a tokenized sentence (i.e. a list of token), it will keep the tokenization.
