### ISSUE TITLE
ImportError: cannot import name 'TrainTransformersNER' from 'tner'

### ISSUE THREAD

**Issue by sangasangasanga** [asahi417/tner#29]
Hi, I was trying your TNER finetuning demo.ipynb. I keep getting this error.
![image](https://user-images.githubusercontent.com/34553270/190044123-56095b6f-c908-4e74-b394-08b35bbcdd9f.png)

I installed tner few times already using different virenv.

**Comment by JanFreise** [comment]
i ran into the same trouble. that's the code from the OLD version 0.0.8. 
If you still want to still use that you need to install this version. 
( This does not output any accuray/f1-value values however since adam does seem to work anymore. )

**Comment by asahi417** [comment]
Hi both, 
Sorry for late, but the colab notebook relies on the old version. I will update it as soon as possible
Asahi

**Comment by asahi417** [comment]
Hi both,

Just updated the Colab notebook demo.
https://colab.research.google.com/drive/1AlcTbEsp8W11yflT7SyT0L4C4HG6MXYr?usp=sharing

**Comment by asahi417** [comment]
It should work but let me know if you have any issues!
