### ISSUE TITLE
Add Mac M1 Support 

### ISSUE THREAD

**Issue by dpicca** [asahi417/tner#30]
First thanks for this great job.

May I ask you to add "mps" support?

for the time being I did a "quick and dirty" fix adding 

`self.device= 'mps' if torch.backends.mps.is_available() == True else 'cpu'`

after this line 

https://github.com/asahi417/tner/blob/971bb6ff43c62bdfbb1f1793e69d15f4a592f90f/tner/ner_model.py#L83

and this

` logging.info(f' GPUs is available? {torch.backends.mps.is_available()}')`

after this

https://github.com/asahi417/tner/blob/971bb6ff43c62bdfbb1f1793e69d15f4a592f90f/tner/ner_model.py#L91

It doesn't always work (for example with Roberta it doesn't work but not because of T-Ner) but it seems to work most of the time.

Thanks

**Comment by asahi417** [comment]
@dpicca Hi, `tner==0.1.7` is now supporting Mac M1. Please check it!

**Comment by JanFreise** [comment]
something is going wrong now

     82         self.device = 'cuda' if torch.cuda.device_count() > 0 else 'cpu'
     83         # Mac M1 Support https://github.com/asahi417/tner/issues/30
---> 84         self.device = 'mps' if torch.backends.mps.is_available() else 'cpu'
     85         self.parallel = torch.cuda.device_count() > 1
     86 

AttributeError: module 'torch.backends' has no attribute 'mps'

**Comment by asahi417** [comment]
I think you should upgrade your pytorch version according to here https://github.com/pytorch/pytorch/issues/78343

**Comment by JanFreise** [comment]
Thanks, will try this. 
This means T-TNER 0.1.7 now has the setup - prerequiste to install/run at least PyTorch version: 1.13.0.
(Google Colab by default still uses 1.12.1+cu113 )

> I think you should upgrade your pytorch version according to here [pytorch/pytorch#78343](https://github.com/pytorch/pytorch/issues/78343)

**Comment by asahi417** [comment]
I feel it's safe to stick to the original one and put the M1 support as an optional, so in version 0.1.8, I reverted it to what used to be before. 

***Only if you need M1 support***, please update the pytorch version accordingly so that your pytorch has the method `torch.backends.mps` and TNER will automatically switch to the M1 device if it's available.

**Comment by asahi417** [comment]
> Thanks, will try this. This means T-TNER 0.1.7 now has the setup - prerequiste to install/run at least PyTorch version: 1.13.0.dev20220525 which was not officially released yet? (Google Colab by default still uses 1.12.1+cu113 )
> 
> > I think you should upgrade your pytorch version according to here [pytorch/pytorch#78343](https://github.com/pytorch/pytorch/issues/78343)

Accordingly, please use version 0.1.8 where you can run without any change to the pytorch version.
