### ISSUE TITLE
Impossible to select GPU in linux

### ISSUE THREAD

**Issue by tednaseri** [asahi417/tner#33]
Hi @asahi417, thank you so much for such a great library. 
I have an issue with choosing the processing device correctly. I am using ubuntu with GPU and the following piece of code, always set CPU as the device.
The logic behind this code seems to throw exceptions when we call `torch.backends.mps.is_available()` in case of working with **other OS than Mac.** But I have found torch just returns False in my use case (Ubuntu 22.04, Geforce 3060). As a result, the device would be set by `CPU` all the time.

**Original code:**
```
        # GPU setup
        try:
            # Mac M1 Support https://github.com/asahi417/tner/issues/30
            self.device = 'mps' if torch.backends.mps.is_available() else 'cpu'
        except Exception:
            self.device = 'cuda' if torch.cuda.device_count() > 0 else 'cpu'
```

**Potential solution:**
```
        # GPU setup
        try:
            # Mac M1 Support https://github.com/asahi417/tner/issues/30
            self.device = 'mps' if torch.backends.mps.is_available() else 'cpu'
        except Exception:
            pass
        if self.device == 'cpu':
            self.device = 'cuda' if torch.cuda.device_count() > 0 else 'cpu'
```

**Comment by asahi417** [comment]
Thanks! Just fixed the code accordingly, and reflected to the pypi package too.

https://pypi.org/project/tner/0.2.0/

**Comment by tednaseri** [comment]
Thank you, that's great
