### ISSUE TITLE
Question about the labels of entities

### ISSUE THREAD

**Issue by CamilleSchr** [asahi417/tner#9]
Hi,

This is not an issue but a question :)
I used your tool and I see a label of an entity that I never say : type': 'facility'
What is the definition of the label 'facility' please ? I can't find any documentation of the labels definitions...

Thank you,
Cheers,
Camille

**Comment by CamilleSchr** [comment]
Found it : https://catalog.ldc.upenn.edu/docs/LDC2013T19/OntoNotes-Release-5.0.pdf

**Comment by asahi417** [comment]
Hi, thanks for the feedback and actually I haven't mentioned very much about the label definition of released models. So, the best way so far to find an entity definition of released models are to refer the original dataset's description

FYI, for the released models, we have a shared entity type that maps entities from every original dataset to our own surface form that can be found here.

https://github.com/asahi417/tner/blob/master/tner/get_dataset.py#L32
